// AddGame actions
export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const FETCH_RESULTS_FAILED = 'FETCH_RESULTS_FAILED';

export const SELECT_GAME = 'SELECT_GAME';
export const REMOVE_SELECTED_GAME = 'REMOVE_SELECTED_GAME';

export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';
export const CHANGE_ENJOYMENT = 'CHANGE_ENJOYMENT';
export const CHANGE_COMMENT_INPUT = 'CHANGE_COMMENT_INPUT';

export const ADD_PLAYED_YEAR = 'ADD_PLAYED_YEAR';
export const REMOVE_PLAYED_YEAR = 'REMOVE_PLAYED_YEAR';
export const CHANGE_PLAYED_YEAR_YEAR = 'CHANGE_PLAYED_YEAR_YEAR';
export const CHANGE_PLAYED_YEAR_AMOUNT = 'CHANGE_PLAYED_YEAR_AMOUNT';

// Auth actions
export const TOKEN_AUTH_SUCCESS = 'AUTH_SUCCESS';
export const LEAVE_PAGE = 'LEAVE_PAGE';
export const LOGOUT = 'LOGOUT';

// Log In actions
export const LOGIN_CHANGE_INPUT = 'LOGIN_CHANGE_INPUT';
export const LOGIN_DESELECT_INPUT = 'LOGIN_DESELECT_INPUT';
export const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Sign Up actions
export const SIGNUP_CHANGE_INPUT = 'SIGNUP_CHANGE_INPUT';
export const SIGNUP_DESELECT_INPUT = 'SIGNUP_DESELECT_INPUT';
export const SIGNUP_SUBMIT = 'SIGNUP_SUBMIT';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

// General user content
export const GET_USER_CONTENT = 'GET_USER_CONTENT';

// Home actions
export const SHOW_HOME_STORIES = 'SHOW_HOME_STORIES';
