// AddGame actions
export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const FETCH_RESULTS_FAILED = 'FETCH_RESULTS_FAILED';

export const SELECT_GAME = 'SELECT_GAME';
export const REMOVE_SELECTED_GAME = 'REMOVE_SELECTED_GAME';

export const CHANGE_PLATFORM = 'CHANGE_PLATFORM';
export const CHANGE_ENJOYMENT = 'CHANGE_ENJOYMENT';
export const CHANGE_COMMENT_INPUT = 'CHANGE_COMMENT_INPUT';

export const ADD_PLAYED_YEAR = 'ADD_PLAYED_YEAR';
export const REMOVE_PLAYED_YEAR = 'REMOVE_PLAYED_YEAR';
export const CHANGE_PLAYED_YEAR_YEAR = 'CHANGE_PLAYED_YEAR_YEAR';
export const CHANGE_PLAYED_YEAR_AMOUNT = 'CHANGE_PLAYED_YEAR_AMOUNT';
