// AddGame actions
export const CHANGE_SEARCH_INPUT = 'CHANGE_SEARCH_INPUT';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const FETCH_RESULTS_FAILED = 'FETCH_RESULTS_FAILED';

export const SELECT_GAME = 'SELECT_GAME';
export const REMOVE_SELECTED_GAME = 'REMOVE_SELECTED_GAME';
